### ISSUE TITLE
Use new AWS SDK

### ISSUE THREAD

**Issue by Nopik** [meinestadt/glue-schema-registry#114]
When I imported this library to my project, I've started to receive following warnings:

```
(node:54303) NOTE: The AWS SDK for JavaScript (v2) will be put into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
```

**Comment by felix-iw** [comment]
I decided to use the SDK v2 instead of v3 because it's pre-installed in the Lambda execution environment.
So it doesn't need to be bundled into the package what keeps it small.
With v3 AWS decided to split up the SDK into many modules, which is a good design choice from my point of view, but requires to include it into the Lambda package. 

But if AWS is really going to retire v2, it's no question that we have to migrate at some point.

**Comment by felix-iw** [comment]
I just found out that the SDK v3 is now included in the node18 lambda runtime.
So developers now can choose whether they want to use the pre-installed SDK or bundle it with their application.
I think there is nothing left holding us off from migrating to v3.

**Comment by Nopik** [comment]
That's great!
