### ISSUE TITLE
Fetching schemas without a local copy

### ISSUE THREAD

**Issue by alexmk92** [meinestadt/glue-schema-registry#311]
Hey I'm pretty new to the Kafka/streaming ecosystem so please forgive me if I'm way off the mark on this question 

In AWS I have a schema pre built in schema registry that we manage/version in terraform 

Currently in my consumer application, I also maintain a local copy of the schema, when schema.register is called it fetches the schema from the registry and allows me to produce messages (great).

If the schema changes, I currently have to make changes in two places if I want to use the latest schema version (in Glue I'd amend the schema and then in my application I have to update the schema to use the latest version)

Is there a way to call registry.get("schemaName", "version") instead?  This would fetch the specific schema from glue and return it to the consumer application (if version is omitted, the latest version would be returned)

If this is a feature that makes sense, I'd happily look at contributing too, I just wanted some validation on if it's a good idea or not given how new I am to this space

Thanks!

**Comment by diegoceldran** [comment]
Hi, it would be great to have this call.

I'm pretty new to kafka too and i create one schema in AWS glue and i can get the version_id of this schema and encoding the message doing registry.encode(SCHEMA_ID, object).

 The problem i have is in consumer. I need a local copy of the schema to decode the message and i need to do the same that i can do in encode method. Instead of pass all the schema to decode() method i like to pass the schema_id and the decode method download the schema from glue.

Is this possible? Maybe i'm asking a dumb question, i have very low time with kafka.

thanks for all!

**Comment by felix-iw** [comment]
Thanks for raising that question. I would suggest to change (evolute) the schema locally, and then let this library and glue do the rest. When you change the schema locally, glue would detect the change and automatically create a new version if the new schema meets the compatibility requirements. 

Consumers normally read the unique schema id from the incoming message and then load the schema from glue. This is also something this library cares about. So in case the glue schema of the consuming application is newer than the local one, the library would load the new schema from glue and try to convert the dataset into the local schema. 
I hope that explanation helps.

**Comment by felix-iw** [comment]
It's also important to have a clear schema evolution strategy. Think about who updates first, the producer or the consumers? Decide what compatibility mode to use (BACKWARD, FORWARD, ALL etc).
The idea behind kafka (or other streaming/messaging solution) in combination with a schema registry is to decouple producer and consumer and allow to evolute the schema without having to modify all producers and consumers at the same time.
For example, you may have one producer and X consumers. You may want to change the schema in the producer first, and later in the producers. To make that work, consumers must be able to consume messages in a schema they don't know yet.
And that's exactly what this library can be used for. For example, when you change the schema in the producer, the library would automatically register a new version in AWS glue (if it meets the compatibility settings).
The consumers, who also use this library to decode the messages, would recognize that a new schema version was used and then load the new schema version from Glue. During decoding of the message, the data gets converted into the older consumer schema automatically (the new schema must be backward compatible so that the automatic conversion works).

Of course, you could do it the other way around also, and change the consumers first (FORWARD compatible schemas). In that case, a consumer would be able to convert an older dataset into the new schema - which would allow you to update the consumers first.

In your application, you normally don't have to "actively" manage schema versions. The library/glue automatically detects the local version that's being used. It also takes care of registering a new version, if needed.
And, last but not least, it takes care of converting messages from the producers schema into the consumers schema.

**Comment by alexmk92** [comment]
Thanks for the thorough explanation Felix, this makes a lot of sense.

My initial use case of wanting to expose a `find` method was because we author realtime data to a clients S3 bucket in Avro format.  I currently have to send them our current agreed version of the schema every time we make changes. 

They had initially asked if we could give them direct access to our schema registry so they could query the latest version on their end whenever they wanted to upgrade.

Having a find method would purely serve as a convenience helper when operating backward compatible schemas, right now, we have 3 consumers on the same evro encoded topic - it would be nice to simply change the `VERSION` environment variable so that when the consumer tries to decode a message it would go to the registry and return `<SCHEMA>:<VERSIOM>` (or `<LATEST>` in the absence of a `<VERSION>` env)...the tradeoff here (and I guess which is why you recommend maintaining a local copy o the schema) is that you lose visibility and type-completion on the schema returned from Glue.

**Comment by felix-iw** [comment]
I think you should include the ID of the used schema with the message data that you write to S3. That's what this library does, it creates a binary data package that contains the schema ID and the payload.
Insted of writing it to Kafka, you can write it to S3. The advantage is, that each dataset contains the ID of the schema it was encoded with. That makes it possible to store or process data from different schema version within the same bucket and consuming application.
For consuming the dataset, your client needs to use the same library (or one that is compatible). The library would take care of loading the correct schema from the schema registry.
But giving your client access to the Glue schema registry might be a bit tricky. Currently it's not possible to share a glue schema registry with another AWS account.
But I see two possible solutions:
1) you can encapsulate the Glue schema registry in a custom webservice
2) you can create an IAM role your client can assume

I would prefer the second option.

Of course we can also add a method for loading a specific version of a schema. But I'm not sure if such a feature should really be part of the library. The main purpose of the library is to make encoding and decoding of messages easy, and handle registration and loading of schemas and their versions automatically.
For simply loading a specific schema version one could use the AWS SDK instead.

**Comment by alexmk92** [comment]
Thanks Felix, this has been really useful - I'm closing the issue as I agree that the goal of my request doesn't meet the intentions of the package.
